### ISSUE TITLE
The browser page appears blank

### ISSUE THREAD

**Issue by Loora1N** [attify/firmware-analysis-toolkit#73]
I was trying to emulate the firmware, but the browser page was blank. The fat.py ran successfully, and I can see it by nmap. 
![image](https://user-images.githubusercontent.com/102774816/190562479-ae9fa31d-9ca9-4daa-bcf2-37a16d802bf0.png)
![image](https://user-images.githubusercontent.com/102774816/190562588-e7869d62-5442-4bb2-aaf6-435152d56d4d.png)
The output was repeat `firmadyne: ioctl: 0x4`
```[  283.524000] firmadyne: ioctl: 0x4
[  283.524000] firmadyne: ioctl: 0x4
[  283.528000] firmadyne: ioctl: 0x4
[  283.532000] firmadyne: ioctl: 0x4
[  283.836000] firmadyne: ioctl: 0x6
[  283.836000] firmadyne: ioctl: 0x6
device ioctl:: Operation not supported
Read wlan sta info failed!
Read wlan sta info failed!
[  284.540000] firmadyne: ioctl: 0x4
[  284.540000] firmadyne: ioctl: 0x4
[  284.540000] firmadyne: ioctl: 0x4
[  284.540000] firmadyne: ioctl: 0x4
[  284.840000] firmadyne: ioctl: 0x6
[  284.840000] firmadyne: ioctl: 0x6
device ioctl:: Operation not supported
Read wlan sta info failed!
Read wlan sta info failed!
[  285.544000] firmadyne: ioctl: 0x4
[  285.544000] firmadyne: ioctl: 0x4
[  285.544000] firmadyne: ioctl: 0x4
[  285.544000] firmadyne: ioctl: 0x4
[  285.848000] firmadyne: ioctl: 0x6
[  285.848000] firmadyne: ioctl: 0x6
device ioctl:: Operation not supported
[mld6.c 1117] implement this
Read wlan sta info failed!
Read wlan sta info failed! 
```

Here is the file.
[DIR822A1_FW103WWb03.zip](https://github.com/attify/firmware-analysis-toolkit/files/9580920/DIR822A1_FW103WWb03.zip)

**Comment by asabhish** [comment]
I tried to emulate your firmware file (D-Link DIR822) and it works for me correctly. I am getting the web admin page at 192.168.0.1. I have trying to emulate a couple of DD-WRT firmware for TP-Link WR841N since long, but the best I get is to login through command line sometimes. Mostly it is some semaphore issue in a loop! Attaching the screenshot of the login page below:

![DLINK_DIR_22_login_page](https://user-images.githubusercontent.com/93587364/195562485-78b2f6f4-3da8-48f5-bc95-eefa7832fbf8.png)

**Comment by extremecoders-re** [comment]
Just ran the provided firmware [DIR822A1_FW103WWb03.zip](https://github.com/attify/firmware-analysis-toolkit/files/9580920/DIR822A1_FW103WWb03.zip) with fat. It works without issues.
